
/*
Auto-generated by CVXPYgen on June 12, 2024 at 14:41:56.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_param9284(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_param9283(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+12] = val;
  Canon_Outdated.b = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_b(){
  for(i=0; i<39; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<50; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.var9281[0] = ecos_workspace->x[1];
  CPG_Prim.var9281[1] = ecos_workspace->x[2];
  CPG_Prim.var9281[2] = ecos_workspace->x[3];
  CPG_Prim.var9281[3] = ecos_workspace->x[4];
  CPG_Prim.var9281[4] = ecos_workspace->x[5];
  CPG_Prim.var9281[5] = ecos_workspace->x[6];
  CPG_Prim.var9281[6] = ecos_workspace->x[7];
  CPG_Prim.var9281[7] = ecos_workspace->x[8];
  CPG_Prim.var9281[8] = ecos_workspace->x[9];
  CPG_Prim.var9281[9] = ecos_workspace->x[10];
  CPG_Prim.var9281[10] = ecos_workspace->x[11];
  CPG_Prim.var9281[11] = ecos_workspace->x[12];
  CPG_Prim.var9281[12] = ecos_workspace->x[13];
  CPG_Prim.var9281[13] = ecos_workspace->x[14];
  CPG_Prim.var9281[14] = ecos_workspace->x[15];
  CPG_Prim.var9281[15] = ecos_workspace->x[16];
  CPG_Prim.var9281[16] = ecos_workspace->x[17];
  CPG_Prim.var9281[17] = ecos_workspace->x[18];
  CPG_Prim.var9281[18] = ecos_workspace->x[19];
  CPG_Prim.var9281[19] = ecos_workspace->x[20];
  CPG_Prim.var9281[20] = ecos_workspace->x[21];
  CPG_Prim.var9281[21] = ecos_workspace->x[22];
  CPG_Prim.var9281[22] = ecos_workspace->x[23];
  CPG_Prim.var9281[23] = ecos_workspace->x[24];
  CPG_Prim.var9281[24] = ecos_workspace->x[25];
  CPG_Prim.var9281[25] = ecos_workspace->x[26];
  CPG_Prim.var9281[26] = ecos_workspace->x[27];
  CPG_Prim.var9281[27] = ecos_workspace->x[28];
  CPG_Prim.var9281[28] = ecos_workspace->x[29];
  CPG_Prim.var9281[29] = ecos_workspace->x[30];
  CPG_Prim.var9281[30] = ecos_workspace->x[31];
  CPG_Prim.var9281[31] = ecos_workspace->x[32];
  CPG_Prim.var9281[32] = ecos_workspace->x[33];
  CPG_Prim.var9281[33] = ecos_workspace->x[34];
  CPG_Prim.var9281[34] = ecos_workspace->x[35];
  CPG_Prim.var9281[35] = ecos_workspace->x[36];
  CPG_Prim.var9281[36] = ecos_workspace->x[37];
  CPG_Prim.var9281[37] = ecos_workspace->x[38];
  CPG_Prim.var9281[38] = ecos_workspace->x[39];
  CPG_Prim.var9282[0] = ecos_workspace->x[40];
  CPG_Prim.var9282[1] = ecos_workspace->x[41];
  CPG_Prim.var9282[2] = ecos_workspace->x[42];
  CPG_Prim.var9282[3] = ecos_workspace->x[43];
  CPG_Prim.var9282[4] = ecos_workspace->x[44];
  CPG_Prim.var9282[5] = ecos_workspace->x[45];
  CPG_Prim.var9282[6] = ecos_workspace->x[46];
  CPG_Prim.var9282[7] = ecos_workspace->x[47];
  CPG_Prim.var9282[8] = ecos_workspace->x[48];
  CPG_Prim.var9282[9] = ecos_workspace->x[49];
  CPG_Prim.var9282[10] = ecos_workspace->x[50];
  CPG_Prim.var9282[11] = ecos_workspace->x[51];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = ecos_workspace->y[0];
  CPG_Dual.d0[1] = ecos_workspace->y[1];
  CPG_Dual.d0[2] = ecos_workspace->y[2];
  CPG_Dual.d1[0] = ecos_workspace->y[3];
  CPG_Dual.d1[1] = ecos_workspace->y[4];
  CPG_Dual.d1[2] = ecos_workspace->y[5];
  CPG_Dual.d2 = ecos_workspace->y[2];
  CPG_Dual.d3[0] = ecos_workspace->y[6];
  CPG_Dual.d3[1] = ecos_workspace->y[7];
  CPG_Dual.d3[2] = ecos_workspace->y[8];
  CPG_Dual.d4 = ecos_workspace->y[5];
  CPG_Dual.d5[0] = ecos_workspace->y[9];
  CPG_Dual.d5[1] = ecos_workspace->y[10];
  CPG_Dual.d5[2] = ecos_workspace->y[11];
  CPG_Dual.d6 = ecos_workspace->y[8];
  CPG_Dual.d7[0] = ecos_workspace->y[12];
  CPG_Dual.d7[1] = ecos_workspace->y[13];
  CPG_Dual.d7[2] = ecos_workspace->y[14];
  CPG_Dual.d8 = ecos_workspace->y[11];
  CPG_Dual.d9[0] = ecos_workspace->y[15];
  CPG_Dual.d9[1] = ecos_workspace->y[16];
  CPG_Dual.d9[2] = ecos_workspace->y[17];
  CPG_Dual.d10 = ecos_workspace->y[14];
  CPG_Dual.d11[0] = ecos_workspace->y[18];
  CPG_Dual.d11[1] = ecos_workspace->y[19];
  CPG_Dual.d11[2] = ecos_workspace->y[20];
  CPG_Dual.d12 = ecos_workspace->y[17];
  CPG_Dual.d13[0] = ecos_workspace->z[21];
  CPG_Dual.d13[1] = ecos_workspace->z[22];
  CPG_Dual.d13[2] = ecos_workspace->z[23];
  CPG_Dual.d14 = ecos_workspace->z[20];
  CPG_Dual.d15[0] = ecos_workspace->z[24];
  CPG_Dual.d15[1] = ecos_workspace->z[25];
  CPG_Dual.d15[2] = ecos_workspace->z[26];
  CPG_Dual.d16 = ecos_workspace->z[23];
  CPG_Dual.d17[0] = ecos_workspace->z[27];
  CPG_Dual.d17[1] = ecos_workspace->z[28];
  CPG_Dual.d17[2] = ecos_workspace->z[29];
  CPG_Dual.d18 = ecos_workspace->z[26];
  CPG_Dual.d19[0] = ecos_workspace->z[30];
  CPG_Dual.d19[1] = ecos_workspace->z[31];
  CPG_Dual.d19[2] = ecos_workspace->z[32];
  CPG_Dual.d20 = ecos_workspace->z[29];
  CPG_Dual.d21[0] = ecos_workspace->z[33];
  CPG_Dual.d21[1] = ecos_workspace->z[34];
  CPG_Dual.d21[2] = ecos_workspace->z[35];
  CPG_Dual.d22 = ecos_workspace->z[32];
  CPG_Dual.d23[0] = ecos_workspace->z[36];
  CPG_Dual.d23[1] = ecos_workspace->z[37];
  CPG_Dual.d23[2] = ecos_workspace->z[38];
  CPG_Dual.d24 = ecos_workspace->z[35];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (ecos_workspace->info->pcost);
  CPG_Info.iter = ecos_workspace->info->iter;
  CPG_Info.status = ecos_flag;
  CPG_Info.pri_res = ecos_workspace->info->pres;
  CPG_Info.dua_res = ecos_workspace->info->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<64; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<123; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<39; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<86; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<50; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!ecos_workspace  ) {
    cpg_copy_all();
    ecos_workspace = ECOS_setup(64, 50, 39, 36, 1, (int *) &ecos_q, 0, Canon_Params_conditioning.G->x, Canon_Params_conditioning.G->p, Canon_Params_conditioning.G->i, Canon_Params_conditioning.A->x, Canon_Params_conditioning.A->p, Canon_Params_conditioning.A->i, Canon_Params_conditioning.c, Canon_Params_conditioning.h, Canon_Params_conditioning.b);
  } else {
    if ( Canon_Outdated.A||Canon_Outdated.b||Canon_Outdated.G) {
      cpg_copy_all();
      ECOS_updateData(ecos_workspace, Canon_Params_conditioning.G->x, Canon_Params_conditioning.A->x, Canon_Params_conditioning.c, Canon_Params_conditioning.h, Canon_Params_conditioning.b);
    } else {
      if ( Canon_Outdated.h) {
        cpg_copy_h();
        for (i=0; i<50; i++) { ecos_updateDataEntry_h(ecos_workspace, i, Canon_Params_conditioning.h[i]); };
      }
    }
  }
  ecos_workspace->stgs->feastol = Canon_Settings.feastol;
  ecos_workspace->stgs->abstol = Canon_Settings.abstol;
  ecos_workspace->stgs->reltol = Canon_Settings.reltol;
  ecos_workspace->stgs->feastol_inacc = Canon_Settings.feastol_inacc;
  ecos_workspace->stgs->abstol_inacc = Canon_Settings.abstol_inacc;
  ecos_workspace->stgs->reltol_inacc = Canon_Settings.reltol_inacc;
  ecos_workspace->stgs->maxit = Canon_Settings.maxit;
  // Solve with ECOS
  ecos_flag = ECOS_solve(ecos_workspace);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.b = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.feastol = 1e-8;
  Canon_Settings.abstol = 1e-8;
  Canon_Settings.reltol = 1e-8;
  Canon_Settings.feastol_inacc = 1e-4;
  Canon_Settings.abstol_inacc = 5e-5;
  Canon_Settings.reltol_inacc = 5e-5;
  Canon_Settings.maxit = 100;
}

void cpg_set_solver_feastol(cpg_float feastol_new){
  Canon_Settings.feastol = feastol_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_feastol_inacc(cpg_float feastol_inacc_new){
  Canon_Settings.feastol_inacc = feastol_inacc_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_maxit(cpg_int maxit_new){
  Canon_Settings.maxit = maxit_new;
}
