
/*
Auto-generated by CVXPYgen on June 12, 2024 at 14:41:56.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_param9284(0, -0.71855038480321209438);
  cpg_update_param9283(0, 0.89930463467384680332);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<39; i++) {
    printf("var9281[%d] = %f\n", i, CPG_Result.prim->var9281[i]);
  }
  for(i=0; i<12; i++) {
    printf("var9282[%d] = %f\n", i, CPG_Result.prim->var9282[i]);
  }

  // Print dual solution
  for(i=0; i<3; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", CPG_Result.dual->d2);
  for(i=0; i<3; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  printf("d4 = %f\n", CPG_Result.dual->d4);
  for(i=0; i<3; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  printf("d6 = %f\n", CPG_Result.dual->d6);
  for(i=0; i<3; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  printf("d8 = %f\n", CPG_Result.dual->d8);
  for(i=0; i<3; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  printf("d10 = %f\n", CPG_Result.dual->d10);
  for(i=0; i<3; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  printf("d12 = %f\n", CPG_Result.dual->d12);
  for(i=0; i<3; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  printf("d14 = %f\n", CPG_Result.dual->d14);
  for(i=0; i<3; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  printf("d16 = %f\n", CPG_Result.dual->d16);
  for(i=0; i<3; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  printf("d18 = %f\n", CPG_Result.dual->d18);
  for(i=0; i<3; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  printf("d20 = %f\n", CPG_Result.dual->d20);
  for(i=0; i<3; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  printf("d22 = %f\n", CPG_Result.dual->d22);
  for(i=0; i<3; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  printf("d24 = %f\n", CPG_Result.dual->d24);

  return 0;

}
